### ISSUE TITLE
filters_editor plugin: todo

### ISSUE THREAD

**Issue by ysard** [labsquare/cutevariant#140]
Problems to be solved:

- [x] Default item in combobox should inform that the user needs to add a filter "Add a filter by pressing '+' or modifying VQL and save it" or "please add a filter" or "current not saved filter:"
=> something like this. currently it is so hard to guess how to use it

- [x] Set a default incremental name on every new filter
(currently blank names)

- [x] When a user has saved a filter, and when he edits the VQL, this filter is updated
BUT when another filter is selected, the previous is not saved.
=> when a user modifies VQL AND when a filter is active, we MUST switch back to the default (not saved) one in order to avoid confusion.

- [x] LIKE operator is quite hard to use
If i want to get all variants with a comment : `comment not like ""` is not possible.
BTW we should think about writing a usage doc for this... You are dealing with biologists not geeks :p
In my upcoming changes i added a variable "__long_description__" to every plugins. It will be used to display a full help on demand.

- [x] When a combox box is selected in the filter (field, operator, value), no changed signal is emitted.
=> we have to click on another combobox so that the modification is taken into account.
=> this should be automatic after click

- [x] In release of June 2019, it was possible to do set operations with registered filters (as selections).
This is not possible anymore. Is it wanted or forgotten ? I think it was a nice feature.
A user should select a filter to do a set operation, and after that, the result is displayed and the correct filter is selected in filter combobox.

- [x] Deletion button should be implemented like that:
https://github.com/ysard/cutevariant/blob/939ebbdee10df2e1049b1382c2f0623bf13eb6dc/cutevariant/gui/plugins/filters_editor/widgets.py#L1560-L1566
    - if filter is saved => delete filter
    - if filter is not saved => clear

- [x] We should purpose a list of pre-made most commonly used filters (remove transcripts with low impact etc.)

- [x] Filters are not saved in the project as selection
=> provide a shortcut for that (same as in variant_view)

- [x] Filters are not saved from a run to another.
=> Maybe we could have a special table for filters; this will help to reload filters when the soft is executed and import/export them.

**Comment by dridk** [comment]
for vql doc https://github.com/labsquare/cutevariant/wiki/VQL-language

Actually the only way to create a selection is from vql. I don't know where to put the button for that.

**Comment by dridk** [comment]
Cannot fix that without your pull request. Seems you move FilterDialog somewhere else.

**Comment by ysard** [comment]
FieldDialog is removed from fields.py since it was the last thing that seems to be useful in this file (data was moved into plugin): ab75df5d738bc2002a3c342f2545ace8771e158f

**Comment by dridk** [comment]
What about creating a dialog to add new filter ?

**Comment by ysard** [comment]
Une boite de dialogue comme avant ? ça me semblait bien mais actuellement il suffit de propager les events de changement des combobox et d'avoir des noms distincts pour les filtres.

Je complète la todolist sur ce plugin au fur et à mesure. C'est un des plugins les plus importants et il ne fonctionne pas.

**Comment by ysard** [comment]
Filters are not saved in the project; they were saved as selection before...

**Comment by dridk** [comment]
So, Briefly for this plugin , we must show a field editor : 
Field is a tuple of 3 elements  : the field_name, the operator and the field_value : 

### Field_name : 

a variant field name (str) :  chr, pos 
an annotation field name (str) :  annotations.gene, gene 
a sample field  (tuple) :  (sample,sacha,gt)

How to edit the last ? 
- Convert the tuple to string  (sample,sacha,gt)  -->  sample['sacha'].gt 
- User can edit from raw text  ? 
- Create a special widget with 2 combobox  :    <sample> <field> ? 


### operator: 
Depend on the type of the field_name. 
For instance, it cannot be possible to do :  "gene" > 10

### field_value : 
integer, float, string can be display into a text edit. 
What about value with IN operator :    gene IN ("boby", "CFTR") ? 
What about value with IN SET operator : gene in SET["truc"] ? 

Using QLineEdit action could help ! 

![image](https://user-images.githubusercontent.com/1911063/95449631-55c12400-0965-11eb-8664-16dc590f84c7.png)

**Comment by ysard** [comment]
> How to edit  sample['sacha'].gt

For now it's ok, the auto-completion is useful and i think we must let the user select this.
The question is also valid for WORDSET['xxx'] syntax. But here we haven't auto-completion.
I'm currently going on the implementation of a special operator (only for the ui for now): IN WORDSET.

> operator choice

Yes, masking operators is an idea; The FieldFactory (which is repaired but not used for now) could be used for that.
Groups of operators matching types of fields could be made.
I will let this idea here for now.

> What about value with IN operator : gene IN ("boby", "CFTR") ?

IterableField is currently implemented and parse with success such data.

> What about value with IN SET operator : gene in SET["truc"] ?

See above

**Comment by ysard** [comment]
I reproduce the question of the topic here, because it's one of the last issues to be resolved before closing this thread: 
Can someone give a set of filters used in routine that I can integrate by default into the software?

I think it's a mistake to think that users will make their own filters especially if they don't have pre-designed examples in front of them.

**Comment by dridk** [comment]
Where impact = 'HiGH'

**Comment by ysard** [comment]
Done. We can move this issue to the next release. It's done for Mendel.
