### ISSUE TITLE
[geneviewer] todo 

### ISSUE THREAD

**Issue by dridk** [labsquare/cutevariant#248]
- [ ] Use the default cursor.. It looks wired to always have the horizontal double arrow cursor
- [x] Remove exon number from exon bar. It must only appear on button
- [x] Some lolipop have no circle. Probably when count_var = 0. Use count_var  + 1 
- [ ] Draw a legend. I have no idea what the meaning of color. Set color with impact

**Comment by SteampunkIslande** [comment]
For lollipops with no circle, let's add a constant. So we have :
thickness = (count_var / sample_count) * 20 +10

**Comment by SteampunkIslande** [comment]
Drawing the legend did a mess in the code...

**Comment by dridk** [comment]
Duplicated with #243
